### ISSUE TITLE
Internal server error after deploy (Lambda arch conflict)

### ISSUE THREAD

**Issue by shyamvalsan** [ricardo-vaca/serverless-fastapi#1]
Thanks for this project - makes things so much easier. 

The make steps work without glitch but I run into an internal server error when I visit the URL, I see the following log in Lambda
`
IMAGE	Launch error: fork/exec /lambda-entrypoint.sh: exec format error	Entrypoint: [/lambda-entrypoint.sh]	Cmd: [app.main.handler]	WorkingDir: [/var/task]`

Any idea what's going on here @ricardo-vaca ?

**Comment by ricardo-vaca** [comment]
I have some points that you can consider:
1. Did you already check if the docker image is being uploaded correctly?
2. Enable the CloudWatch service and search the lambda's logs and please upload some screenshots in this thread.
3. Try changing the version of 'public.ecr.aws/lambda/python:3.8' (Dockerfile) to a newer.

I also just tried re-building the entire project and I got no problems. I'm currently using 
```
- Terraform v1.2.6
- Docker v20.10.17, build 100c701
- Python v3.10.5
- MacOS with M1 processor.
```

Another thing that you can try is building the docker image with ARM64 architecture -> https://www.docker.com/blog/multi-arch-images/

**Comment by shyamvalsan** [comment]
@ricardo-vaca Here's the logs from CloudWatch

![image](https://user-images.githubusercontent.com/24860547/211542754-5ecbdd91-3625-4041-afd4-b43bb42cadc6.png)

Docker image appears to have uploaded correctly - there were no errors, there were a couple of warnings during the `make ecr` stage. 
```

aws_ecr_repository.serverless_fastapi_repository: Creating...
aws_ecr_repository.serverless_fastapi_repository: Creation complete after 1s [id=serverless_fastapi_container]
╷
│ Warning: Resource targeting is in effect
│
│ You are creating a plan with the -target option, which means that the result of this plan may not represent all of the changes requested by the current configuration.
│
│ The -target option is not for routine use, and is provided only for exceptional situations such as recovering from errors or mistakes, or when Terraform specifically suggests to use it as part of an error
│ message.
╵
╷
│ Warning: Applied changes may be incomplete
│
│ The plan was created with the -target option in effect, so some changes requested in the configuration may have been ignored and the output values may not be fully updated. Run the following command to
│ verify that no other changes are pending:
│     terraform plan
│
│ Note that the -target option is not suitable for routine use, and is provided only for exceptional situations such as recovering from errors or mistakes, or when Terraform specifically suggests to use it as
│ part of an error message.

```

I haven't tried changing the version of python in Dockerfile to something newer. I'll give that a shot too, but would be surprised if that's what's causing this.

**Comment by ricardo-vaca** [comment]
The issue could be appearing because of this -> The ```"architectures = ['arm64']``` line. Try commenting/deleting this line or just change the string to ```"x86_64"``` instead of ```"arm64"```

![image](https://user-images.githubusercontent.com/106180152/211589786-52926a47-dee2-43ea-a04f-ed82337a3ced.png)

As I commented before: Another thing that you can try is building the docker image with ARM64 architecture -> https://www.docker.com/blog/multi-arch-images/
